name: homecredit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.8.0
  riverpod: ^2.6.1
  state_notifier: ^1.0.0
  http: ^1.4.0
  intl: ^0.19.0
  hooks_riverpod: ^2.6.1
  implicitly_animated_reorderable_list_2: ^0.6.0

  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  generate: true
